
print("=====================")
print("--BEST FRIEND MAKER--")
print("=====================")
print("")
print("Hi. I'm the computer")
print("")
name = input("What is your name? ")
print("")
color = input(f"Hi, {name} What's your favorite color? ")
print("")
print(f"No way! My favorite color is also {color}")
print("")
movie = input("What's your favorite movie? ")
print("")
print(f"What!?! My favorite movie is also {movie}")
print("")
game = input("What is your favorite game? ")
print("")
print(f"Get out of here! My favorite game is {game} too")
print("")
print("We like the same things! We should be best friends!")